### ISSUE TITLE
Does it work in IOS

### ISSUE THREAD

**Issue by Shiba-Kar** [tazik561/alt_sms_auto_fill#1]

**Comment by tazik561** [comment]
Yes, Just support Android.

**Comment by rahmanrezaee** [comment]
Why u put android and ios both??

**Comment by tazik561** [comment]
No, just Android

**Comment by leventkantaroglu** [comment]
Why don't you declare this on read me file, thanks.

According to readme it seems as if it supports both ios and android.

**Comment by tazik561** [comment]
I didn't mention that, but that platform part I guess because there is IOS folder in project, pub dev thought this library support IOS
